const RecoilKeys = {
  PLAYLISTS: "PLAYLISTS",
  PLAYLIST_SELECTOR: "PLAYLIST_SELECTOR",
  TRACKS: "TRACKS",
  TRACKS_BY_PLAYLIST: "TRACKS_BY_PLAYLIST",
  TRACKS_WITH_WORK: "TRACKS_WITH_WORK",
  TRACK_BY_ID: "TRACK_BY_ID",
  TIMESHEETS: "TIMESHEETS",
  TIMESHEET_CURRENT: "TIMESHEET_CURRENT",
  TIMESHEET_BY_ID: "TIMESHEET_BY_ID",
};
export default RecoilKeys;
